### ISSUE TITLE
Debugger connection

### ISSUE THREAD

**Issue by MeLlamoGamer** [zimavi/WinttOS#5]
Hello, i'm trying to boot the new version on WinttOS but it asks me for a debugger connection. What does that mean?

**Comment by zimavi** [comment]
Hello! It seems I forgot to turn the debugger off. I'll rebuild the system and make a new release as soon as possible. Thanks for feedback

Edit: Here is new [release](https://github.com/zimavi/WinttOS/releases/tag/v1.1.0-dev.070520241923)
